### ISSUE TITLE
crash on laodup {1.15.2)

### ISSUE THREAD

**Issue by SDUBZ** [halotroop2288/ex-features-mod#2]
https://paste.ee/p/EocCZ

using version 3.0 from cf

**Comment by halotroop2288** [comment]
Use the hotfix.

**Comment by SDUBZ** [comment]
you might wanna push last build to cf to fix this

**Comment by halotroop2288** [comment]
Dude. Look on CurseForge. It IS there. There's just no way to replace the original file there.
